import { CONTENT_TITLES as DEMO_TITLES, CONTENT_HOOK as DEMO_HOOK, CONTENT_SCRIPT as DEMO_SCRIPT, CONTENT_DESCRIPTION as DEMO_DESC, CONTENT_TAGS as DEMO_TAGS } from '../data/demo.js';
import { api } from '../api/client.js';

export function renderContentStudio(apiData) {
  const pkg = apiData?.package;

  const titles = pkg?.titles || DEMO_TITLES;
  const hook = pkg?.hook || DEMO_HOOK;
  const script = pkg?.script || DEMO_SCRIPT;
  const description = pkg?.description || DEMO_DESC;
  const tags = pkg?.tags || DEMO_TAGS;

  const studioItems = [
    { label: 'Strategy', status: 'done' },
    { label: 'YouTube', status: 'done' },
    { label: 'Short', status: pkg?.short_script ? 'done' : 'draft' },
    { label: 'LinkedIn', status: pkg?.linkedin_post ? 'done' : 'empty' },
    { label: 'X', status: pkg?.x_thread ? 'done' : 'empty' },
    { label: 'Instagram', status: 'empty' },
  ];

  window._saveStudioContent = async function() {
    const selectedTitleEl = document.querySelector('.title-option.selected span');
    const selectedTitle = selectedTitleEl ? selectedTitleEl.innerText : titles[0];
    const hookVal = document.getElementById('hook-editor').value;
    const scriptVal = document.getElementById('script-editor').value;
    const descVal = document.getElementById('desc-editor').value;

    await api.saveContentStudio({
      titles: titles,
      selected_title_index: 0,
      hook: hookVal,
      script: scriptVal,
      description: descVal,
      tags: tags
    });

    _showToast('Content saved to FastAPI Backend!');
  };

  return `
    <div class="page-header">
      <h1 class="page-title">Content Studio</h1>
      <p class="page-desc">Create, edit, and manage your AI-generated content package (Powered by ContentStudioAgent).</p>
    </div>

    <div class="studio-layout">
      <div class="studio-sidebar">
        <div class="studio-sidebar-title">Content Package</div>
        ${studioItems.map((item, i) => `
          <div class="studio-sidebar-item ${i === 1 ? 'active' : ''}" id="studio-item-${i}">
            <span class="status-dot ${item.status}"></span>
            ${item.label}
          </div>
        `).join('')}
      </div>
      <div class="studio-main">
        <div class="studio-section">
          <div style="display:flex;align-items:center;justify-content:space-between;margin-bottom:var(--space-4)">
            <h2 class="studio-section-title" style="margin:0">Title</h2>
            <button class="btn btn-ghost btn-sm" onclick="_showToast('Titles regenerated by agent')"><i data-lucide="refresh-cw"></i>Regenerate</button>
          </div>
          ${titles.map((t, i) => `
            <div class="title-option ${i === 0 ? 'selected' : ''}" id="title-opt-${i}">
              <div class="title-option-radio"></div>
              <span style="font-size:var(--font-size-base);font-weight:var(--font-weight-medium)">${t}</span>
            </div>
          `).join('')}
        </div>

        <div class="studio-section">
          <div style="display:flex;align-items:center;justify-content:space-between;margin-bottom:var(--space-4)">
            <h2 class="studio-section-title" style="margin:0">Hook</h2>
            <button class="btn btn-ghost btn-sm" onclick="_showToast('Hook regenerated')"><i data-lucide="refresh-cw"></i>Regenerate</button>
          </div>
          <textarea class="studio-editor" style="min-height:80px" id="hook-editor">${hook}</textarea>
        </div>

        <div class="studio-section">
          <div style="display:flex;align-items:center;justify-content:space-between;margin-bottom:var(--space-4)">
            <h2 class="studio-section-title" style="margin:0">Script</h2>
            <button class="btn btn-ghost btn-sm" onclick="_showToast('Script regenerated')"><i data-lucide="refresh-cw"></i>Regenerate</button>
          </div>
          <textarea class="studio-editor" id="script-editor">${script}</textarea>
        </div>

        <div class="studio-section">
          <h2 class="studio-section-title">Description</h2>
          <textarea class="studio-editor" style="min-height:120px" id="desc-editor">${description}</textarea>
        </div>

        <div class="studio-section">
          <h2 class="studio-section-title">Tags</h2>
          <div class="tag-input-wrap">
            ${tags.map(t => `<span class="tag">${t} <span style="cursor:pointer;opacity:.6">×</span></span>`).join('')}
            <input class="input" style="border:none;background:transparent;flex:1;min-width:80px;padding:var(--space-1)" placeholder="Add tag..." />
          </div>
        </div>

        <div style="display:flex;gap:var(--space-3);padding-top:var(--space-4);border-top:1px solid var(--border-primary)">
          <button class="btn btn-primary" onclick="_saveStudioContent()"><i data-lucide="save"></i>Save Content</button>
          <button class="btn btn-secondary" onclick="_showToast('Regenerated by ContentStudioAgent')"><i data-lucide="refresh-cw"></i>Regenerate All</button>
        </div>
      </div>
    </div>
  `;
}
